SecondProject/app/urls.py
from django.urls import path
from django.views.generic import YearArchiveView

from . import views
from .views import *

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("show_r", views.show_rubric, name="show_r"),
    path("show_m", views.show_measurement, name="show_m"),
    path("set_an", views.set_announcement, name="set_an"),
    path("show_b", views.show_board, name="show_b"),
    path("onetoone", views.OneToOne, name="onetoone"),
    path("manytomany", views.ManyToMany, name="manytomany"),
    path("try_bulk_create", views.try_bulk_create, name="try_bulk_create"),
    path("try_bulk_update", views.try_bulk_update, name="try_bulk_update"),
    path("clear_bb_content", views.clear_bb_content, name="clear_bb_content"),
    path("check_full_clean", views.check_full_clean, name="check_full_clean"),
    path("just_print_results", views.just_print_results, name="just_print_results"),
    path("check_functions_2", views.check_functions_2, name="check_functions_2"),
    path("calculate_fields", views.calculate_fields, name="calculate_fields"),
    path(
        "check_other_functions",
        views.check_other_functions,
        name="check_other_functions",
    ),
    path(
        "access_to_related_records",
        views.access_to_related_records,
        name="access_to_related_records",
    ),
    path("write_some_func/", WriteSomeFunctions.as_view(), name="write_some_func"),
    path("rubrics/", RubricListView.as_view(), name="rubric_list"),
    path("rubric/<int:rubric_id>", views.by_rubric, name="by_rubric"),
    path("add/", views.add_bb_and_save, name="add"),
    path("send_file/", views.send_file, name="send_file"),
    path("detailw/<int:bb_id>", views.detailw, name="detailw"),
    path("detail2/<int:rubric_id>", views.detail2, name="detail2"),
    path("check_resolve", views.check_resolve, name="check_resolve"),
    # re_path - шаблонные выражения, как и re в Python
    path("add_class/", BbCreateView.as_view()),
    path(
        "templateview_check/<int:rubric_id>",
        BbByRubricView.as_view(),
        name="bb_by_rubric",
    ),
    path("detail/<int:pk>", BbDetailView.as_view(), name="detail"),
    path(
        "detail/<int:year>/<int:month>/<int:day>/<int:pk>",
        BbRedirectView.as_view(),
        name="old_detail",
    ),
    path("list/<int:rubric_id>", BbByRubricViewList.as_view(), name="list"),
    path("add_form/", BbAddView.as_view(), name="add_form"),
    path("edit/<int:pk>", BbEditView.as_view(), name="edit"),
    path("delete<int:pk>", BbDeleteView.as_view(), name="delete"),
    path("archive/", BbIndexView.as_view(), name="archive"),
    path(
        "<int:year>/",
        YearArchiveView.as_view(
            model=Bb, date_field="created_at", make_object_list=True
        ),
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<int:pk>",
        BbDateDetailView.as_view(),
        name="datedetail",
    ),  # Также создает шаблон с суффиксом detail, как и DetailView, но надо указывать slug или pk в url
    path(
        "detailclass/<int:rubric_id>", BbByRubricMixinView.as_view(), name="detailclass"
    ),
    path("add_class_form/", BbCreateFormView.as_view()),
    path("register_user/", RegisterUserFormView.as_view(), name="register_user"),
    path("rubrics/edit/", views.rubrics, name="rubric_set"),
    path("bbs_list/<int:rubric_id>", views.bbs, name="bbs_list"),
    path("tests/", views.test_select_prefetch_related),
    path("tests_through/", views.test_through_in_models),
    path("poly/", views.polymorfic_relations),
    path("send_m/", views.view_inherent_models),
    path("abs_prox/", views.test_abstract_and_proxy_models),
    path("test_manager/", views.test_dispatcher_manager),
    path("search/", views.search, name="search"),
    path("search_formset/", views.formset_proccessing, name="search_formset"),
    path("add_comment/<int:bb_pk>", views.write_comment, name="add_comment"),
    path(
        "pgsroom-reserving/create/",
        views.create_pgsroomserving,
        name="pgsroom_reservation_create",
    ),
    path("pgs-rubric/create/", views.create_pgsrubric, name="pgs_rubric_create"),
    path("pgs-project/create/", views.create_pgsproject, name="pgs_project_create"),
]

SecondProject/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("accounts/", include("accounts.urls")),
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SecondProject/app/templates/app/archive_index.html
{% extends 'basic.html' %}
{% load static %}

{% block title %} Архив {% endblock %}

{% block content %}

<h3> Какие дни есть:</h3>
<ul>
    {% for d in date_list %}
    <li> {{ d|date:"Y-m-d" }}</li>
    {% empty %}
    <li> Нет доступных дат</li>
    {% endfor %}
</ul>

{% endblock %}

SecondProject/app/templates/app/bb_archive_year.html
{%extends 'basic.html' %}
{% load static %}

{% block title %} Ohhh...shit, here we go again... {% endblock %}

{% block content %}

Дэйт: {{ year }}
<ul>
{% for bb in object_list %}<li>{{ bb.title }} - {{ bb.created_at|date:"Y-m-d" }}</li>
{% empty %}<li>Нет объявлений за этот год</li>
{% endfor %}
</ul>

{% endblock %}

SecondProject/app/templates/app/bb_detail.html
{% extends 'basic.html' %}
{% load static %}

{% block title %} {{ bb.title }} {% endblock %}

{% block content %}

<p> Рубрика: {{ bb.rubric_name }}</p>
<h2>{{ bb.title }} </h2>
<p>{{ bb.content }} </p>
<p>Цена: {{ bb.price }} </p>
<p> Паблишед: {{ bb.created_at }}</p>
{% endblock %}

SecondProject/app/templates/app/bb_form.html
{% extends 'basic.html' %}
{% load static %}

{% block title %} Изменяем ббшку {% endblock %}

{% block content %}
<form method="post">
  <h2> Форма ббшки</h2>
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}
  {% if form.non_field_errors %}
  <ul>
    {% for error in form.non_field_errors %}
    <li><em>{{ error|escape }}</em></li>
    {% endfor %}
  </ul>
  {% endif %}
  {% for field in form.visible_fields %}
    {% if field.errors %}
    <ul>
      {% for error in field.error %}
      <li><em>{{ error|escape }}</em></li>
      {% endfor %}
    </ul>
    {% endif %}
  <p>{{ field.label_tag }} <br> {{ field }} <br> {{ field.help_text }}</p>
  {% endfor %}
  <input type="submit" value="Изменить">
</form>
{% endblock %}

SecondProject/app/templates/app/bbs.html
{% extends 'basic.html' %}

{% block content %}
<h1>Редактировать ббшки {{ current_rubric }}</h1>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% if formset.non_form_errors %}
    <ul>
        {% for error in formset.non_form_errors %}
        <li><em>{{ error|escape}}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    <table>
        {% for form in formset %}
        <tr>
            <td>{{ form.id }}</td>
            <td> Название: {{ form.title }}</td>
            {% if formset.can_order %}
                <td> Порядок: {{ form.ORDER }}</td>
            {% endif %}
            {% if formset.can_delete %}
                <td> Удалить: {{ form.DELETE }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Сохранить">
</form>

{% endblock %}

SecondProject/app/templates/app/by_rubric.html
{% extends 'basic.html' %}

{% block title %} {{current_rubric.name }} {% endblock %}

{% block content %}

<h2>Рубрика: {{current_rubric.name }}</h2>
{% for bb in bbs %}
<div>
    <h2>{{ bb.title }}</h2>
    <p>Контент: {{ bb.content }}</p>
    <p>Цена: {{ bb.price }}</p>
    <p> Паблишед: {{ bb.created_at }}</p>
    <p><a href="{% url 'app:edit' pk=bb.pk %}"> Изменить </a></p>
    <p><a href="{% url 'app:delete' pk=bb.pk %}"> Удалить </a></p>
    <p><a href="{% url 'app:add_comment' bb_pk=bb.pk %}"> Оставить комментарий</a></p>
</div>
{% endfor %}
{% endblock %}

SecondProject/app/templates/app/create.html
{% extends 'basic.html' %}


{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send.">
</form>
{% endblock %}

SecondProject/app/templates/app/create_comment.html
{% extends 'basic.html' %}

{% block title %} Add comment {% endblock %}

{% block content %}
<h3>Bb name: {{ bb.title }}</h3>
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="leave a comment.">
</form>
{% endblock %}

SecondProject/app/templates/app/formset.html
{% extends 'basic.html' %}

{% block title %}
Search FormSet
{% endblock %}

{% block content %}
<h2> Fill in multiple search forms</h2>
<form method="POST">
    {% csrf_token %}
    {{ formset.management_form }}

    <table>
        {% for form in formset %}
        <tr>
            {{ form }}
        </tr>
        {% endfor %}
    </table>
    <button type="submit">Search</button>
</form>
{% endblock %}

SecondProject/app/templates/app/process_result.html
{% extends 'basic.html' %}

{% block title %}
Processed Form Data
{% endblock %}

{% block content %}
<h2> Processed Forms: </h2>

<ul>
    {% for form in valid_forms %}
    <li>
        Keyword: {{ form.keyword }} |
        Rubric ID: {{ form.rubric_id }} |
        Order: {{ form.order }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

SecondProject/app/templates/app/register.html
{% extends 'basic.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться.">
</form>
{% endblock %}

SecondProject/app/templates/app/rubric_formset.html
{% extends 'basic.html' %}

{% block content %}
<h1>Редактировать рубрики</h1>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% if formset.non_form_errors %}
    <ul>
        {% for error in formset.non_form_errors %}
        <li><em>{{ error|escape}}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    <table>
        {% for form in formset %}
        <tr>
            <td>{{ form.id }}</td>
            <td> Название: {{ form.name }}</td>
            {% if formset.can_order %}
                <td> Порядок: {{ form.ORDER }}</td>
            {% endif %}
            {% if formset.can_delete %}
                <td> Удалить: {{ form.DELETE }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

SecondProject/app/templates/app/search.html
{% extends 'basic.html' %}

{% block title %}
Find my ckkk...
{% endblock %}


{% block content %}
<form method="POST">
    <h1> Search Bb in rubric.</h1>
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <input type="submit" value="Поиск">
</form>
{% endblock %}

SecondProject/app/templates/app/search_results.html
{% extends 'basic.html' %}

{% block title %}
  Results of Searching. {{ bbs.first.entries.name }}
{% endblock %}

{% block content %}
{% for bb in bbs %}
<h2>Title: {{ bb.title }}</h2>
<h2>Content: {{ bb.content }}</h2>
<h2>Price: {{ bb.price }}</h2>
{% endfor %}
{% endblock %}